import numpy as np


SCREEN_WIDTH = 900
SCREEN_HEIGHT = 750
SCREEN_RESOLUTION = (SCREEN_WIDTH, SCREEN_HEIGHT)

DISPLAY_HEIGHT = DISPLAY_WIDTH = min(SCREEN_RESOLUTION)
DISPLAY_RESOLUTION = (DISPLAY_WIDTH, DISPLAY_HEIGHT)


if __name__ == "__main__":
    pass
    